name: PR checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  conventional-commit-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: infracost/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
